import fs from 'node:fs/promises';
import path from 'node:path';
import Studio from '@/components/Studio';
import type { Manifest } from '@/lib/grid';

/**
 * The manifest is generated by scripts/build-grids.js and committed, so this
 * reads from disk at build time and the page ships fully static.
 */
async function readManifest(): Promise<Manifest> {
  const file = path.join(process.cwd(), 'public', 'grids', 'manifest.json');
  return JSON.parse(await fs.readFile(file, 'utf8')) as Manifest;
}

export default async function Page() {
  const manifest = await readManifest();

  if (manifest.pieces.length === 0) {
    return (
      <main className="flex min-h-dvh items-center justify-center p-8 text-center font-mono text-xs text-koko-dim">
        No grids found. Put images in art/ and run `npm run build:grids`.
      </main>
    );
  }

  return (
    <main>
      <Studio manifest={manifest} />
    </main>
  );
}
